name: my_villo_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/villo_app_icon.png
    - assets/images/villo_logo_wordmark.png
    - assets/images/car.png
    - assets/images/auto.png
    - assets/images/bike.png
    - assets/images/splash_bg.png
    - assets/images/villo_logo.png
    - assets/images/bg_city_village.png
